/* What the stub models answer, by what the system prompt asks: shared by the browser fixture (studio-fixture.mjs) and
 * the backend harnesses, with no browser dependency. MOCKED answers: they prove the wiring, not a model's quality. */
export const RELEASE = 'MEDIA RELEASE - 30 September 2026\n\nFuel tax credits keep regional Australia moving\n\nThe Minerals Council of Australia today released new analysis showing that mining paid $74 billion in company tax and royalties in 2023-24, more than any other industry.\n\nMCA Chief Executive Officer Tania Constable said fuel tax credits were not a subsidy. "Businesses do not pay a road fuel tax on fuel used off-road. The credit simply returns a tax that was never meant to apply," Ms Constable said.\n\nThe analysis found the credit is used by more than 150,000 businesses of all sizes, including farmers, tradies and tourism operators.\n\nENDS';
const LEDGER = { headline: 'Fuel tax credits keep regional Australia moving', claims: [
  { text: 'mining paid $74 billion in company tax and royalties in 2023-24', value: 74, unit: 'billion', subject: 'tax and royalties', period: '2023-24', passage: 'p3' },
  { text: 'the credit is used by more than 150,000 businesses of all sizes', value: 150000, unit: 'businesses', passage: 'p5' }],
  brief: { objective: 'Answer the subsidy framing while the credit is in the news', audience: 'Regional voters and MPs', message: 'The credit is not a subsidy', action: 'Read the facts', deliverables: 'Organic posts' } };
const DIRS = { directions: [
  { title: 'The plain ask', message: 'The credit is not a subsidy; it returns a tax that never applied.', insight: 'Subsidy sounds like a handout.', headline: 'Not a subsidy. A tax that never applied.', opening: 'Fuel tax credits are not a subsidy.', visual: 'Restrained documentary photography of a regional road', rationale: 'Plain language', claims: ['c1'], uncertainty: 'No figure for the credit itself' },
  { title: 'Who it really is', message: 'The credit is used by 150,000 businesses of all sizes.', insight: 'Naming tradies moves the frame.', headline: 'Farmers. Tradies. Tourism operators.', opening: 'Who uses the fuel tax credit?', visual: 'A tradie at a rural bowser', rationale: 'Approved usage wording', claims: ['c2'], uncertainty: 'Portraits need releases' }] };
const T = (id, role, x, y, w, h, size, extra) => Object.assign({ id, type: 'text', role, x, y, w, h, size, color: '#FFFFFF' }, extra || {});
/* a photographic plan (a background region the image model fills) and a typographic one (no imagery at all) */
const PHOTO_PLAN = { medium: 'photo-documentary', approach: 'editable', mark: 'campaign', regions: [{ id: 'bg', role: 'background', x: 0, y: 0, w: 100, h: 100, prompt: 'A quiet regional road at dusk, no machinery, open sky in the upper third' }],
  elements: [{ id: 'panel', type: 'shape', role: 'panel', shape: 'rect', x: 5, y: 56, w: 70, h: 36, fill: '#0E6A6E', opacity: 0.92 }, T('hl', 'headline', 8, 59, 64, 16, 5.2), T('sp', 'support', 8, 76, 64, 8, 2.6), T('cta', 'cta', 8, 85, 40, 5, 2.4)] };
const TYPE_PLAN = { medium: 'typographic', approach: 'editable', mark: 'campaign', bg: '#0E6A6E', regions: [],
  elements: [{ id: 'rule', type: 'shape', role: 'rule', shape: 'rect', x: 8, y: 14, w: 18, h: 1.2, fill: '#F4F1EA' }, T('hl', 'headline', 8, 20, 84, 30, 6.4), T('sp', 'support', 8, 56, 70, 12, 2.8), T('cta', 'cta', 8, 74, 50, 6, 2.6)] };
const HEAD = { linkedin: 'Not a subsidy. A tax that never applied.', facebook: 'Not a subsidy. A tax that never applied.', instagram: 'Farmers, tradies and tourism operators use it', x: 'Not a subsidy.' };
const pieces = user => { const none = /NO IMAGERY/.test(user); return { pieces: ['linkedin', 'facebook', 'instagram', 'x'].filter(c => new RegExp('- ' + c + ' \\(').test(user)).map(c => ({ channel: c, headline: HEAD[c], support: 'Businesses do not pay a road fuel tax on fuel used off-road.', cta: 'Get the facts', caption: 'Mining paid $74 billion in company tax and royalties in 2023-24, more than any other industry.', alt: 'Teal fact panel over a regional road at dusk', visual: 'Regional road at dusk', claims: ['c1'], hashtags: [], plan: JSON.parse(JSON.stringify(none ? TYPE_PLAN : PHOTO_PLAN)) })) }; };
const decide = user => { const A = Array.from(user.matchAll(/^\[(a[a-z0-9]+)\]/gm)).map(m => m[1]); const ins = (user.match(/TEAM LEAD[^\n]*\):\n([^\n]+)/) || [])[1] || '';
  if (/adapt/i.test(ins)) { const want = /story|9:16/i.test(ins) ? { channel: 'instagram', format: '9:16' } : { channel: 'x', format: '16:9' }; return { kind: 'adapt', reply: 'Adapted the master for ' + want.format + ', the words kept.', adapt: { from: A[0], pieces: [Object.assign({}, want, { copy: { caption: 'Not a subsidy. A road tax that never applied.', alt: 'the same tile, re-composed for ' + want.format } })] }, memory: { standing: false } }; }
  // the Copy step's partner asks for headlines offered as alternatives (S13)
  if (/headlines? for this piece as alternatives|offer it as alternatives/i.test(ins)) return { kind: 'alternatives', reply: 'Three headlines, the claim kept.', alternatives: { asset: A[0], field: 'headline', options: ['Not a subsidy. Never was.', 'A road tax that never applied.', 'Off-road fuel pays no road tax.'] }, memory: { standing: false } };
  return { kind: 'text', reply: 'Headline sharpened; layout and image kept.', changes: [{ asset: A[0], copy: { headline: 'Not a subsidy. Never was.' }, note: 'sharper' }], memory: { standing: false } }; };
const CONCEPTS = { critique: 'The words sit low; the sky is unused.', options: [
  { name: 'Right column', concept: 'Words in the quiet right third', rationale: 'The eye lands on the road first', composition: 'right column', keeps: ['photograph', 'words'], changes: ['placement'], plan: { medium: 'photo-documentary', approach: 'editable', mark: 'campaign', regions: [{ id: 'bg', role: 'background', x: 0, y: 0, w: 100, h: 100, prompt: 'keep the current image' }], elements: [{ id: 'col', type: 'shape', role: 'panel', shape: 'rect', x: 58, y: 0, w: 42, h: 100, fill: '#0E6A6E', opacity: 0.85 }, T('hl', 'headline', 61, 8, 36, 40, 4.6), T('sp', 'support', 61, 52, 36, 20, 2.6), T('cta', 'cta', 61, 80, 36, 6, 2.4)] } },
  { name: 'Top band', concept: 'A band across the sky', rationale: 'The road keeps the lower two thirds', composition: 'top band', keeps: ['photograph', 'words'], changes: ['panel'], plan: { medium: 'photo-documentary', approach: 'editable', mark: 'campaign', regions: [{ id: 'bg', role: 'background', x: 0, y: 0, w: 100, h: 100, prompt: 'keep the current image' }], elements: [{ id: 'band', type: 'shape', role: 'panel', shape: 'rect', x: 0, y: 0, w: 100, h: 36, fill: '#0E6A6E' }, T('hl', 'headline', 5, 4, 90, 16, 4.6), T('sp', 'support', 5, 21, 62, 8, 2.4), T('cta', 'cta', 70, 24, 26, 6, 2.4)] } }] };
const INSPECT = { fidelity: 4, hierarchy: 3, readability: 4, relevance: 4, identity: 4, reasons: { fidelity: 'The road carries the regional idea', hierarchy: 'The support line competes with the headline', readability: 'White on teal reads', relevance: 'Regional fuel use is the subject', identity: 'Teal and the mark are the campaign' }, words: { present: [], wrong: [] }, issues: [{ text: 'The support line sits close to the headline', severity: 'minor' }], verdict: 'fix', fix: { kind: 'design', instruction: 'Add a line of space between the headline and the support line; keep everything else.' }, note: 'Close; one spacing fix.' };
const SUGGEST = { design: [{ text: 'Move the panel to the right third and let the road lead.', why: 'The subject is covered', refs: [] }], image: [{ text: 'The same road a little later, the sky quieter.', why: 'Room for the words' }] };
const STRATEGY = { problem: 'Voters hear subsidy and assume a handout.', audience: { who: 'Regional voters', now: 'It is a handout', wanted: 'It is a road tax never meant for off-road fuel', insight: 'Farmers claim the same credit' }, idea: 'It is your tractor too', proposition: 'Not a subsidy: a road tax returned', proof: [], tone: 'plain, regional', avoid: [], risks: [], measures: [], questions: [] };
/* the brief engine (S15): paragraphs about fuel, mining or the regions are kept, the rest set aside as another client's */
const analysis = user => {
  const paras = Array.from(user.matchAll(/^\[P(\d+)\] (.*)$/gm)).map(m => ({ p: 'P' + m[1], text: m[2] }));
  const mine = x => /fuel|mining|minerals|tractor|regional|royalt/i.test(x.text);
  const camp = (user.match(/^CAMPAIGNS \(\d+\):\n- ([a-z0-9_-]+): /m) || [])[1] || null; const f1 = /^\[F1\]/m.test(user);
  return { summary: 'The fuel tax credit is back in the news; the rest of the material concerns other clients.', kind: 'daily',
    relevant: paras.filter(mine).map(x => ({ p: x.p, why: 'the fuel tax credit, a client issue' })), filtered: paras.filter(x => !mine(x)).slice(0, -1).map(x => ({ p: x.p, why: 'another client\'s issue' })),
    campaign: { id: camp, confidence: 0.82, why: 'the credit is the national campaign\'s core argument' },
    brief: { objective: 'Answer the subsidy framing while the credit is in the news', audience: 'Regional voters and MPs', message: 'The credit is not a subsidy', action: 'Read the facts', channels: ['linkedin', 'instagram'], deliverable: 'set', tone: 'plain' },
    claims: [{ text: 'mining paid $74 billion in company tax and royalties', p: (paras.find(mine) || {}).p || 'P1', status: f1 ? 'matches_fact' : 'new_unverified', fact: f1 ? 'F1' : '' }, { text: 'the credit costs $10 billion a year', p: 'P1', status: 'conflicts_fact', fact: 'F9' }],
    knowledge: [{ k: 'K1', use: 'the approved line on off-road fuel' }],
    angles: [{ headline: 'Not a subsidy. A tax that never applied.', line: 'Off-road fuel never used the roads it was taxed for.', why: 'answers the frame head on' }, { headline: 'The subsidy myth', line: 'It is a subsidy, they say.', why: 'names the myth' }],
    input: { type: /daily brief/i.test(user) ? 'daily_brief' : 'news', why: 'several stories, one of them ours' },
    understanding: { situation: { v: 'A crossbencher called the fuel tax credit a subsidy for miners', basis: 'stated' }, audience: { v: 'Regional voters and MPs', basis: 'inferred' }, urgency: { v: 'high', basis: 'inferred' }, keyMessage: { v: 'The credit is not a subsidy', basis: 'knowledge' }, cta: { v: 'Read the facts', basis: 'inferred' }, stakeholders: { v: 'Senate crossbench; regional radio', basis: 'stated' } },
    situation: { what: 'A Senate crossbencher called the fuel tax credit a subsidy for miners; regional radio picked it up.', whyItMatters: 'The subsidy frame is the one the national campaign exists to correct, and it is spreading in the regions the campaign targets.', kinds: ['misinformation', 'campaign'], respond: /DO NOT RESPOND/.test(user) ? 'no' : 'yes', why: 'the frame is spreading and the facts are on our side' },
    topics: [{ name: 'Fuel tax credits', kind: 'issue', relevance: 'high', issue: 'ftc', why: 'the client issue itself' }, { name: 'Senate crossbench', kind: 'topic', relevance: 'potential', issue: '', why: 'who said it' }, { name: 'Gas reservation', kind: 'issue', relevance: 'not', issue: 'gasres', why: 'another client' }],
    comparison: { new: ['a crossbencher has adopted the subsidy frame'], known: ['the subsidy myth (K1)'], supports: ['F1 tax paid'], contradicts: [], campaignAffected: 'the national campaign', narrative: { state: 'existing', ref: 'N1', why: 'the subsidy narrative is live' }, alreadyCommunicated: 'yes, in the myth-busting series', publicDiscussion: 'regional radio', gaps: ['no regional spokesperson named'], missingContext: ['what the crossbencher proposes'], conflicts: [], briefImprovements: ['name the channel and the deadline'], cites: ['K1', 'F1', 'Z9'] },
    intelSummary: 'An existing myth has found a new voice in the Senate; answer it with the tax-paid fact, regionally, today.',
    objectives: [{ title: 'Correct the subsidy claim before it settles in the regions', kind: 'correct', why: 'the frame is spreading', messages: [{ primary: 'The fuel tax credit is not a subsidy', supporting: 'It returns a road tax on fuel that never touches a public road.', evidence: ['F1', 'P2', 'Q7'], proof: 'tax paid', takeaway: 'it is fair', emotion: 'reassured', reaction: 'shares the fact', cta: 'Read the facts' }, { primary: 'Mining pays its way', supporting: '$74 billion in company tax and royalties.', evidence: ['F1'], proof: 'F1', takeaway: 'miners pay', emotion: 'pride', reaction: 'agrees', cta: 'See the figures' }] },
      { title: 'Reinforce the national campaign position', kind: 'reinforce', why: 'continuity', messages: [{ primary: 'Hands off our fuel', supporting: 'Regional jobs run on diesel.', evidence: [], proof: '', takeaway: '', emotion: '', reaction: '', cta: 'Join us' }] }],
    strategies: [{ kind: 'evidence', objective: 'O1', audience: 'regional voters', message: 'The credit is not a subsidy', benefit: 'facts settle it', risk: 'amplifies the claim', urgency: 'high', platforms: ['facebook', 'linkedin'], format: 'myth vs fact card', recommended: true }, { kind: 'indirect', objective: 'O2', audience: 'MPs', message: 'Regional jobs', benefit: 'no amplification', risk: 'slower', urgency: 'medium', platforms: ['linkedin'], format: 'statement', recommended: false }, { kind: 'none', objective: '', audience: '', message: '', benefit: 'no oxygen', risk: 'the claim stands', urgency: 'low', platforms: [], format: '', recommended: false }],
    directions: [{ name: 'The quiet road', approach: 'data', core: 'A road nobody drove, taxed anyway', relevance: 'figures must be exact', audience: 'regional voters', objective: 'O1', message: 'M1.1', strategy: 'S1', response: 'shares the fact', hook: 'A tax for roads it never used', visualIdea: 'an empty regional road at dawn', platforms: ['facebook'], risks: ['looks defensive'], evidence: ['F1', 'P2'], headlines: ['A tax for roads it never used', 'Not a subsidy. A tax that never applied.', 'Off-road fuel, on-road tax'], captions: ['Off-road fuel never used the roads it was taxed for.', 'The credit returns a road tax.'], format: 'myth_fact', medium: 'photo-documentary', route: 'editable', routeWhy: 'figures must be exact', visual: { scene: 'an empty regional road at dawn', composition: 'words in the sky third', lighting: 'low gold sun', typography: 'condensed bold headline', textPlacement: 'top third', ctaPlacement: 'bottom right' } },
      { name: 'One striking poster', approach: 'campaign_continuation', core: 'The myth crossed out in paint', relevance: 'one settled line', audience: 'supporters', objective: 'O2', message: 'M2.1', strategy: 'S2', response: 'shares', hook: 'Not a subsidy', visualIdea: 'a painted poster', platforms: ['instagram'], risks: [], evidence: [], headlines: ['Not a subsidy', 'Myth, crossed out'], captions: ['Hands off our fuel.'], format: 'headline_artwork', medium: 'editorial', route: 'finished', routeWhy: 'one settled line, one hero image', visual: { scene: 'a hand-painted poster', artDirection: 'bold brush', colour: 'campaign teal and gold' } }],
    recommendation: { strategy: 'S1', objective: 'O1', message: 'M1.1', direction: 1, why: 'facts are on our side and the regions are where it is spreading' },
risks: ['opponents call any defence of the credit a defence of a handout'], gaps: [], next: { stage: 'copy', why: 'the brief is clear and a campaign matched' } };
};
const KIT = user => ({ items: Array.from((user.match(/WRITE: ([^\n]+)/) || [])[1].matchAll(/([a-z_]+) = /g)).map(m => ({ kind: m[1], title: m[1].replace(/_/g, ' '), body: m[1] === 'statement' ? 'The fuel tax credit is not a subsidy. Mining paid $74 billion in company tax and royalties.' : m[1] === 'talking_points' ? '1. It is not a subsidy.\n2. It returns a road tax.\n3. It costs $99 billion a year.' : 'Hands off our fuel: the credit returns a tax that never applied.', evidence: ['F1', 'P2', 'X9'], note: 'from the chosen direction' })) });
const TRANSCRIBE = { title: 'Crossbencher post', kind: 'social', paragraphs: ['The fuel tax credit is a subsidy for miners and it has to go.', 'Posted by a Senate crossbencher, 6 October.'], visual: 'A screenshot of a social post with a Senate portrait.', unreadable: '' };
/* S17: a guided project's directions carry the card fields (hook, audience, tone, why, risks, platforms, layout, visual narrative,
   route); refine and merge answer with one direction; alternatives with ones unlike the standing set */
const DIRS2 = [
  { title: 'The plain ask', idea: 'Say plainly what the credit is', message: 'The credit is not a subsidy; it returns a tax that never applied.', audience: 'Regional voters', tone: 'plain, calm', hook: 'Not a subsidy. Never was.', headline: 'Not a subsidy. A tax that never applied.', opening: 'Fuel tax credits are not a subsidy.', why: 'It answers the frame head on with the approved line', risks: ['repeats the word subsidy'], platforms: ['facebook', 'linkedin'], layout: 'Headline top third, fact panel low, mark bottom right', medium: 'typographic', composition: 'type-led', typography: 'condensed bold', colour: 'teal and cream', visual: 'type and colour only', visualNarrative: { scene: 'no photograph: type on teal', typography: 'condensed bold headline', textPlacement: 'top third', ctaPlacement: 'bottom left' }, route: 'editable', claims: ['c1'], renders: 0 },
  { title: 'Who it really is', idea: 'Name the people who use it', message: 'The credit is used by 150,000 businesses of all sizes.', audience: 'Regional voters and MPs', tone: 'warm', hook: 'Farmers. Tradies. Tourism operators.', headline: 'Farmers. Tradies. Tourism operators.', opening: 'Who uses the fuel tax credit?', why: 'Naming tradies moves the frame from miners to neighbours', risks: ['portraits need releases'], platforms: ['instagram', 'facebook'], layout: 'Portrait full bleed, headline in a low band', medium: 'photo-documentary', composition: 'portrait with low band', typography: 'bold sans', colour: 'natural light', visual: 'A tradie at a rural bowser at dusk', visualNarrative: { scene: 'a rural bowser at dusk', subject: 'a tradie filling a ute', lighting: 'low gold sun', textPlacement: 'low band', ctaPlacement: 'band right' }, route: 'editable', claims: ['c2'], renders: 1 },
  { title: 'The road never driven', idea: 'Show the road the fuel never touches', message: 'Off-road fuel never used the roads it was taxed for.', audience: 'Supporters', tone: 'striking', hook: 'A tax for roads it never used', headline: 'A tax for roads it never used', opening: 'The fuel never touched the road.', why: 'One striking image carries the whole argument', risks: ['looks like an ad'], platforms: ['instagram'], layout: 'One hero image, words painted in the sky', medium: 'photo-cinematic', composition: 'hero image', typography: 'large display', colour: 'dawn palette', visual: 'An empty regional road at dawn', visualNarrative: { scene: 'an empty road at dawn', lighting: 'low dawn light', textPlacement: 'sky third', ctaPlacement: 'bottom right' }, route: 'finished', claims: [], renders: 1 }];
const dirsFor = (sys, user) => {
  if (!/CONFIRMED objective/.test(sys)) return DIRS;
  if (/REFINE this direction/.test(user)) return { directions: [Object.assign({}, DIRS2[0], { title: 'The plain ask, sharper', hook: 'Not a subsidy. Not now, not ever.', headline: 'Not a subsidy. Not now, not ever.' })] };
  if (/MERGE these directions/.test(user)) return { directions: [Object.assign({}, DIRS2[1], { title: 'Neighbours, plainly', idea: 'The people who use it, said plainly', headline: 'Your neighbours use it. It is not a subsidy.', medium: 'editorial' })] };
  if (/ALTERNATIVES\./.test(user)) return { directions: [Object.assign({}, DIRS2[2], { title: 'The ledger', idea: 'The tax paid, as a ledger', medium: 'infographic', headline: '$74 billion paid', route: 'editable' })] };
  const n = Math.max(1, Math.min(3, parseInt((user.match(/Give (\d) direction/) || [])[1], 10) || 3));
  return { directions: DIRS2.slice(0, n) };
};
export function answerFor(sys, user) {
  return /message kit from ONE chosen creative direction/.test(sys) ? KIT(user) : /You read an uploaded/.test(sys) ? TRANSCRIBE : /strategy lead of an Australian political communications agency/.test(sys) ? analysis(user) : /creative strategist/.test(sys) ? STRATEGY : /build a claim ledger/.test(sys) ? LEDGER : /genuinely different directions/.test(sys) ? dirsFor(sys, user) : /producing a coordinated set/.test(sys) ? pieces(user) : /decide what the instruction asks/.test(sys) ? decide(user) : /suggesting the next things the team might ask for/.test(sys) ? SUGGEST : /art director inspecting a rendered social tile/.test(sys) ? INSPECT : /art director of an Australian political communications agency/.test(sys) ? CONCEPTS : {};
}

export { LEDGER, DIRS, PHOTO_PLAN, TYPE_PLAN, CONCEPTS, INSPECT, SUGGEST, STRATEGY };
