/* What the stub models answer, by what the system prompt asks: shared by the browser fixture (studio-fixture.mjs) and
 * the backend harnesses, with no browser dependency. MOCKED answers: they prove the wiring, not a model's quality. */
export const RELEASE = 'MEDIA RELEASE - 30 September 2026\n\nFuel tax credits keep regional Australia moving\n\nThe Minerals Council of Australia today released new analysis showing that mining paid $74 billion in company tax and royalties in 2023-24, more than any other industry.\n\nMCA Chief Executive Officer Tania Constable said fuel tax credits were not a subsidy. "Businesses do not pay a road fuel tax on fuel used off-road. The credit simply returns a tax that was never meant to apply," Ms Constable said.\n\nThe analysis found the credit is used by more than 150,000 businesses of all sizes, including farmers, tradies and tourism operators.\n\nENDS';
const LEDGER = { headline: 'Fuel tax credits keep regional Australia moving', claims: [
  { text: 'mining paid $74 billion in company tax and royalties in 2023-24', value: 74, unit: 'billion', subject: 'tax and royalties', period: '2023-24', passage: 'p3' },
  { text: 'the credit is used by more than 150,000 businesses of all sizes', value: 150000, unit: 'businesses', passage: 'p5' }],
  brief: { objective: 'Answer the subsidy framing while the credit is in the news', audience: 'Regional voters and MPs', message: 'The credit is not a subsidy', action: 'Read the facts', deliverables: 'Organic posts' } };
const DIRS = { directions: [
  { title: 'The plain ask', message: 'The credit is not a subsidy; it returns a tax that never applied.', insight: 'Subsidy sounds like a handout.', headline: 'Not a subsidy. A tax that never applied.', opening: 'Fuel tax credits are not a subsidy.', visual: 'Restrained documentary photography of a regional road', rationale: 'Plain language', claims: ['c1'], uncertainty: 'No figure for the credit itself' },
  { title: 'Who it really is', message: 'The credit is used by 150,000 businesses of all sizes.', insight: 'Naming tradies moves the frame.', headline: 'Farmers. Tradies. Tourism operators.', opening: 'Who uses the fuel tax credit?', visual: 'A tradie at a rural bowser', rationale: 'Approved usage wording', claims: ['c2'], uncertainty: 'Portraits need releases' }] };
const T = (id, role, x, y, w, h, size, extra) => Object.assign({ id, type: 'text', role, x, y, w, h, size, color: '#FFFFFF' }, extra || {});
/* a photographic plan (a background region the image model fills) and a typographic one (no imagery at all) */
const PHOTO_PLAN = { medium: 'photo-documentary', approach: 'editable', mark: 'campaign', regions: [{ id: 'bg', role: 'background', x: 0, y: 0, w: 100, h: 100, prompt: 'A quiet regional road at dusk, no machinery, open sky in the upper third' }],
  elements: [{ id: 'panel', type: 'shape', role: 'panel', shape: 'rect', x: 5, y: 56, w: 70, h: 36, fill: '#0E6A6E', opacity: 0.92 }, T('hl', 'headline', 8, 59, 64, 16, 5.2), T('sp', 'support', 8, 76, 64, 8, 2.6), T('cta', 'cta', 8, 85, 40, 5, 2.4)] };
const TYPE_PLAN = { medium: 'typographic', approach: 'editable', mark: 'campaign', bg: '#0E6A6E', regions: [],
  elements: [{ id: 'rule', type: 'shape', role: 'rule', shape: 'rect', x: 8, y: 14, w: 18, h: 1.2, fill: '#F4F1EA' }, T('hl', 'headline', 8, 20, 84, 30, 6.4), T('sp', 'support', 8, 56, 70, 12, 2.8), T('cta', 'cta', 8, 74, 50, 6, 2.6)] };
const HEAD = { linkedin: 'Not a subsidy. A tax that never applied.', facebook: 'Not a subsidy. A tax that never applied.', instagram: 'Farmers, tradies and tourism operators use it', x: 'Not a subsidy.' };
const pieces = user => { const none = /NO IMAGERY/.test(user); return { pieces: ['linkedin', 'facebook', 'instagram', 'x'].filter(c => new RegExp('- ' + c + ' \\(').test(user)).map(c => ({ channel: c, headline: HEAD[c], support: 'Businesses do not pay a road fuel tax on fuel used off-road.', cta: 'Get the facts', caption: 'Mining paid $74 billion in company tax and royalties in 2023-24, more than any other industry.', alt: 'Teal fact panel over a regional road at dusk', visual: 'Regional road at dusk', claims: ['c1'], hashtags: [], plan: JSON.parse(JSON.stringify(none ? TYPE_PLAN : PHOTO_PLAN)) })) }; };
const decide = user => { const A = Array.from(user.matchAll(/^\[(a[a-z0-9]+)\]/gm)).map(m => m[1]); const ins = (user.match(/TEAM LEAD[^\n]*\):\n([^\n]+)/) || [])[1] || '';
  if (/adapt/i.test(ins)) { const want = /story|9:16/i.test(ins) ? { channel: 'instagram', format: '9:16' } : { channel: 'x', format: '16:9' }; return { kind: 'adapt', reply: 'Adapted the master for ' + want.format + ', the words kept.', adapt: { from: A[0], pieces: [Object.assign({}, want, { copy: { caption: 'Not a subsidy. A road tax that never applied.', alt: 'the same tile, re-composed for ' + want.format } })] }, memory: { standing: false } }; }
  return { kind: 'text', reply: 'Headline sharpened; layout and image kept.', changes: [{ asset: A[0], copy: { headline: 'Not a subsidy. Never was.' }, note: 'sharper' }], memory: { standing: false } }; };
const CONCEPTS = { critique: 'The words sit low; the sky is unused.', options: [
  { name: 'Right column', concept: 'Words in the quiet right third', rationale: 'The eye lands on the road first', composition: 'right column', keeps: ['photograph', 'words'], changes: ['placement'], plan: { medium: 'photo-documentary', approach: 'editable', mark: 'campaign', regions: [{ id: 'bg', role: 'background', x: 0, y: 0, w: 100, h: 100, prompt: 'keep the current image' }], elements: [{ id: 'col', type: 'shape', role: 'panel', shape: 'rect', x: 58, y: 0, w: 42, h: 100, fill: '#0E6A6E', opacity: 0.85 }, T('hl', 'headline', 61, 8, 36, 40, 4.6), T('sp', 'support', 61, 52, 36, 20, 2.6), T('cta', 'cta', 61, 80, 36, 6, 2.4)] } },
  { name: 'Top band', concept: 'A band across the sky', rationale: 'The road keeps the lower two thirds', composition: 'top band', keeps: ['photograph', 'words'], changes: ['panel'], plan: { medium: 'photo-documentary', approach: 'editable', mark: 'campaign', regions: [{ id: 'bg', role: 'background', x: 0, y: 0, w: 100, h: 100, prompt: 'keep the current image' }], elements: [{ id: 'band', type: 'shape', role: 'panel', shape: 'rect', x: 0, y: 0, w: 100, h: 36, fill: '#0E6A6E' }, T('hl', 'headline', 5, 4, 90, 16, 4.6), T('sp', 'support', 5, 21, 62, 8, 2.4), T('cta', 'cta', 70, 24, 26, 6, 2.4)] } }] };
const INSPECT = { fidelity: 4, hierarchy: 3, readability: 4, relevance: 4, identity: 4, reasons: { fidelity: 'The road carries the regional idea', hierarchy: 'The support line competes with the headline', readability: 'White on teal reads', relevance: 'Regional fuel use is the subject', identity: 'Teal and the mark are the campaign' }, words: { present: [], wrong: [] }, issues: [{ text: 'The support line sits close to the headline', severity: 'minor' }], verdict: 'fix', fix: { kind: 'design', instruction: 'Add a line of space between the headline and the support line; keep everything else.' }, note: 'Close; one spacing fix.' };
const SUGGEST = { design: [{ text: 'Move the panel to the right third and let the road lead.', why: 'The subject is covered', refs: [] }], image: [{ text: 'The same road a little later, the sky quieter.', why: 'Room for the words' }] };
const STRATEGY = { problem: 'Voters hear subsidy and assume a handout.', audience: { who: 'Regional voters', now: 'It is a handout', wanted: 'It is a road tax never meant for off-road fuel', insight: 'Farmers claim the same credit' }, idea: 'It is your tractor too', proposition: 'Not a subsidy: a road tax returned', proof: [], tone: 'plain, regional', avoid: [], risks: [], measures: [], questions: [] };
export function answerFor(sys, user) {
  return /creative strategist/.test(sys) ? STRATEGY : /build a claim ledger/.test(sys) ? LEDGER : /genuinely different directions/.test(sys) ? DIRS : /producing a coordinated set/.test(sys) ? pieces(user) : /decide what the instruction asks/.test(sys) ? decide(user) : /suggesting the next things the team might ask for/.test(sys) ? SUGGEST : /art director inspecting a rendered social tile/.test(sys) ? INSPECT : /art director of an Australian political communications agency/.test(sys) ? CONCEPTS : {};
}

export { LEDGER, DIRS, PHOTO_PLAN, TYPE_PLAN, CONCEPTS, INSPECT, SUGGEST, STRATEGY };
