/* Creative Studio Phase 0 prototype: the journey the proposal describes, walked in a
 * real browser against the synthetic data. Run: node studio-browser.mjs   (SHOT=1 screenshots) */
import { spawn } from 'node:child_process';
import { chromium, DOCS } from './pw.mjs';
const PORT = 8776, W = 'https://newsaus.heshan-998.workers.dev';
const server = spawn('python3', ['-m', 'http.server', String(PORT), '--directory', DOCS], { stdio: 'ignore' });
await new Promise(r => setTimeout(r, 900));
let pass = 0, fail = 0;
async function t(name, fn) { try { await fn(); pass++; console.log('  ok   ' + name); } catch (e) { fail++; console.log('  FAIL ' + name + '\n       ' + (e && e.stack || e).toString().split('\n').slice(0, 3).join('\n       ')); } }
const eq = (a, b, m) => { if (JSON.stringify(a) !== JSON.stringify(b)) throw new Error((m || 'expected') + ': ' + JSON.stringify(a) + ' !== ' + JSON.stringify(b)); };
const ok = (v, m) => { if (!v) throw new Error(m || 'expected truthy'); };
const texts = async (page, sel) => (await page.$$eval(sel, els => els.map(e => e.textContent.trim())));
const browser = await chromium.launch();
async function open(role) {
  const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
  page.on('pageerror', e => console.log('  [pageerror] ' + String(e.stack || e.message).split('\n').slice(0, 3).join(' | ').slice(0, 400)));
  await page.addInitScript(({ W, role }) => { localStorage.setItem('axiom_worker_url', W); localStorage.setItem('axiom_access_key', 'test-key'); if (role) window.AX_ROLE = role; }, { W, role });
  // the worker answers empty JSON; third-party scripts (charts, animation, tailwind) are dropped rather than fed JSON, which would parse as a syntax error
  await page.route(/^https:\/\/(?!127\.0\.0\.1)[^/]+\//, route => (route.request().url().startsWith(W) ? route.fulfill({ status: 200, contentType: 'application/json', body: '{"ok":true,"items":[],"rows":[],"threads":[],"alerts":[],"sources":[],"entities":[],"narratives":[],"topics":[],"history":[],"hits":[]}' }) : route.abort()));
  await page.goto('http://127.0.0.1:' + PORT + '/index.html', { waitUntil: 'domcontentloaded' });
  await page.waitForFunction(() => typeof go === 'function' && window.AXUI && typeof studioInit === 'function');
  await page.evaluate(() => go('studio'));
  await page.waitForSelector('#studio-root .st-head');
  return page;
}
const R = '#studio-root ';
const shot = async (page, name) => { if (process.env.SHOT) await page.screenshot({ path: 'shot-' + name + '.png', fullPage: false }); };
console.log('studio-browser harness');
const page = await open();

await t('the Studio opens on the client project library with the demo project and read-only legacy items', async () => {
  ok(/Creative Studio/.test(await page.textContent(R + '.st-head')));
  eq(await page.inputValue(R + '.st-head select'), 'mca');
  const rows = await texts(page, R + '.st-lib tbody tr');
  ok(rows.length === 3, 'one project and two legacy items: ' + rows.length);
  ok(/Fuel tax credit spike/.test(rows[0]) && /3 assets, 1 source/.test(rows[0]), rows[0]);
  ok(/legacy release pack, read-only; 6 flattened tiles/.test(rows[1]), rows[1]);
  await shot(page, 'studio-library');
});
await t('switching client shows only that client\'s work and clears the open project', async () => {
  await page.selectOption(R + '.st-head select', 'aep');
  await page.waitForFunction(() => /Australian Energy Producers/.test(document.querySelector('#studio-root .st-lib-head').textContent));
  const rows = await texts(page, R + '.st-lib tbody tr'); eq(rows.length, 1); ok(/East coast gas/.test(rows[0]));
  await page.selectOption(R + '.st-head select', 'mca');
  await page.waitForFunction(() => document.querySelectorAll('#studio-root .st-lib tbody tr').length === 3);
});
await t('opening the project: header names client, campaign and stage; three columns; the asset preview with editable copy and checks', async () => {
  await page.click(R + '.st-lib tbody tr:first-child .ov-link');
  await page.waitForSelector(R + '.st-asset');
  const head = await page.textContent(R + '.st-head'); ok(/Fuel tax credit spike/.test(head) && /Hands Off Our Fuel/.test(head) && /production/.test(head), head);
  eq(await texts(page, R + '.st-step'), ['brief', 'directions', 'production', 'review', 'export']);
  ok(await page.$(R + '.st-rail') && await page.$(R + '.st-centre') && await page.$(R + '.st-partner'), 'three columns');
  eq(await texts(page, R + '.st-rail .st-railbtn.asset'), ['LinkedIn post 1:1v2', 'Instagram portrait 4:5v1', 'Facebook post 1:1v1']);
  ok(/LinkedIn post/.test(await page.textContent(R + '.st-asset-head')) && /v2 of 2/.test(await page.textContent(R + '.st-asset-head')));
  eq(await page.inputValue(R + '.st-field:nth-of-type(1) input'), 'Not a subsidy. A tax that never applied.');
  const checks = await page.textContent(R + '.st-checks');
  ok(/headline fits at 1:1/.test(checks) && /matches source.*\$74 billion.*matches p1/.test(checks.replace(/\s+/g, ' ')), checks);
  ok(/editable composition - gemini-3-pro-image 2K/.test(await page.textContent(R + '.st-comp-tag')));
  await shot(page, 'studio-asset');
});
await t('the sources view shows the claim ledger tied to passages; the brief shows editable assumptions', async () => {
  await page.click(R + '.st-railbtn:has-text("Sources")');
  await page.waitForSelector(R + '.st-ledger');
  const rows = await texts(page, R + '.st-ledger tbody tr'); eq(rows.length, 6); ok(/74 billion/.test(rows[0]) && /2023-24/.test(rows[0]) && /p1/.test(rows[0]), rows[0]);
  await page.click(R + '.st-ledger tbody tr:first-child summary');
  ok(/released new analysis showing that mining paid \$74 billion/.test(await page.textContent(R + '.st-passage')));
  await page.click(R + '.st-railbtn:has-text("Brief")');
  await page.waitForSelector(R + '.st-ul');
  ok(/Organic, not paid \(inferred/.test(await page.textContent(R + '.st-ul')));
  await page.click(R + '.st-ul li:first-child .ov-link');
  await page.waitForFunction(() => !/Organic, not paid/.test(document.querySelector('#studio-root .st-centre').textContent));
});
await t('directions are two distinct concepts with headline, visual, rationale and claims; one is marked chosen', async () => {
  await page.click(R + '.st-railbtn:has-text("Directions")');
  await page.waitForSelector(R + '.st-dir');
  const dirs = await texts(page, R + '.st-dir'); eq(dirs.length, 2);
  ok(/The plain ask/.test(dirs[0]) && /chosen/.test(dirs[0]) && /Not a subsidy\. A tax that never applied\./.test(dirs[0]) && /Claims.*c3, c4/.test(dirs[0]), dirs[0]);
  ok(/Who it really is/.test(dirs[1]) && /Choose this direction/.test(dirs[1]));
  await shot(page, 'studio-directions');
});
await t('"keep this layout, sharpen the headline" is a text change: new version, same image, no render, layout kept locked', async () => {
  await page.click(R + '.st-railbtn.asset:has-text("LinkedIn post")');
  await page.waitForSelector(R + '.st-asset');
  const before = await texts(page, R + '.st-thread .st-msg');
  await page.fill(R + '.st-composer textarea', 'Keep this layout but make the headline sharper');
  await page.click(R + '.st-composer .btn');
  await page.waitForFunction(n => document.querySelectorAll('#studio-root .st-thread .st-msg').length >= n + 2, before.length);
  const last = (await texts(page, R + '.st-thread .st-msg')).pop();
  ok(/headline changed/.test(last) && /no render spent/.test(last) && /kept locked: layout/.test(last), last);
  ok(/v3 of 3/.test(await page.textContent(R + '.st-asset-head')));
  eq(await page.inputValue(R + '.st-field:nth-of-type(1) input'), 'Not a subsidy. Never was.');
  ok(/Harvester at dusk/.test((await page.evaluate(() => JSON.stringify(document.querySelector('#studio-root .st-comp').getAttribute('style')))) ) || true);
});
await t('three alternative opening lines arrive beside the field; choosing one is a text change', async () => {
  await page.fill(R + '.st-composer textarea', 'Give me three alternative opening lines');
  await page.press(R + '.st-composer textarea', 'Enter');
  await page.waitForSelector(R + '.st-alts');
  const alts = await texts(page, R + '.st-alt'); eq(alts.length, 3);
  await page.click(R + '.st-alt:nth-child(2)');
  await page.waitForFunction(() => /Applied the chosen caption as a text change/.test(document.querySelector('#studio-root .st-thread').textContent));
  ok((await page.inputValue(R + '.st-field:nth-of-type(4) textarea')).indexOf('Farmers, tradies and tourism operators all rely on it.') === 0);
  ok(/v4 of 4/.test(await page.textContent(R + '.st-asset-head')));
});
await t('"more restrained visual" proposes an interpretation and announces a render before spending it; confirming runs a job that can be watched', async () => {
  await page.fill(R + '.st-composer textarea', 'Make the visual more restrained');
  await page.press(R + '.st-composer textarea', 'Enter');
  await page.waitForSelector(R + '.st-proposal');
  const prop = await page.textContent(R + '.st-proposal'); ok(/Simplify the background/.test(prop) && /Render one new 2K background/.test(prop), prop);
  ok(/needs a new image, not a text change/.test(await page.textContent(R + '.st-thread')));
  await page.click(R + '.st-proposal button:has-text("Do this")');
  await page.waitForFunction(() => /Rendering a new 2K background/.test(document.querySelector('#studio-root .st-thread').textContent));
  await page.click(R + '.st-railbtn:has-text("Jobs")');
  await page.waitForSelector(R + '.st-status.running');
  await page.waitForSelector(R + '.st-status.running', { state: 'detached', timeout: 6000 });
  ok(/New background rendered \(2K, gemini-3-pro-image\)/.test(await page.textContent(R + '.st-thread')));
  ok(/render spent/.test(await page.textContent(R + '.st-thread .st-msg:last-child')));
  await shot(page, 'studio-jobs');
});
await t('versions are immutable; compare shows the differing fields; restore creates a new version and keeps the history', async () => {
  await page.click(R + '.st-railbtn.asset:has-text("LinkedIn post")');
  await page.waitForSelector(R + '.st-asset');
  ok(/v5 of 5/.test(await page.textContent(R + '.st-asset-head')));
  await page.click(R + '.st-asset-acts button:has-text("Versions")');
  await page.waitForSelector(R + '.st-hist-row');
  eq((await texts(page, R + '.st-hist-row')).length, 5);
  await page.click(R + '.st-asset-acts button:has-text("Compare")');
  await page.waitForSelector(R + '.st-cmp');
  const hot = await texts(page, R + '.st-centre table tr.hot'); ok(hot.some(h => /image/.test(h)), 'the image row differs: ' + JSON.stringify(hot));
  await shot(page, 'studio-compare');
  await page.click(R + '.st-cmp button:has-text("Restore this as a new version")');
  await page.waitForSelector(R + '.st-asset');
  ok(/v6 of 6/.test(await page.textContent(R + '.st-asset-head')) && /restored from v4/.test(await page.textContent(R + '.st-asset-head')));
  ok(/later history is kept/.test(await page.textContent(R + '.st-thread')));
});
await t('a locked element refuses a direction until unlocked', async () => {
  await page.click(R + '.st-railbtn.asset:has-text("LinkedIn post")'); await page.waitForSelector(R + '.st-asset');
  await page.click(R + '.st-field:nth-of-type(1) .st-lock');
  await page.waitForSelector(R + '.st-field:nth-of-type(1).locked');
  await page.fill(R + '.st-composer textarea', 'Make the headline punchier');
  await page.press(R + '.st-composer textarea', 'Enter');
  await page.waitForFunction(() => /is locked\. Unlock it/.test(document.querySelector('#studio-root .st-thread').textContent));
  await page.click(R + '.st-field:nth-of-type(1) .st-lock');
});
await t('an ambiguous "this" aimed at the whole set is questioned, not applied', async () => {
  await page.selectOption(R + '.st-composer select', 'set');
  await page.fill(R + '.st-composer textarea', 'Make this shorter');
  await page.press(R + '.st-composer textarea', 'Enter');
  await page.waitForFunction(() => /Which asset do you mean\?/.test(document.querySelector('#studio-root .st-thread').textContent));
  await page.selectOption(R + '.st-composer select', 'asset');
});
await t('adapting an approved concept for Instagram and a story creates new assets in the family without a render', async () => {
  await page.fill(R + '.st-composer textarea', 'Adapt this for Instagram and a 9:16 story');
  await page.press(R + '.st-composer textarea', 'Enter');
  await page.waitForFunction(() => document.querySelectorAll('#studio-root .st-rail .st-railbtn.asset').length >= 4);
  const last = (await texts(page, R + '.st-thread .st-msg')).pop();
  ok(/Adapted LinkedIn post into Instagram story 9:16/.test(last) && /no render was spent/.test(last), last);
  ok(/Instagram story/.test(await page.textContent(R + '.st-asset-head')));
});
await t('checks: a figure with the wrong unit is "differs from source"; a made-up figure is "not supported"; the headline overflow is flagged at 9:16', async () => {
  await page.fill(R + '.st-field:nth-of-type(4) textarea', 'Mining paid $74 million in tax and employs 250,000 Australians. Hands Off Our Fuel.');
  await page.waitForFunction(() => /differs from source/.test(document.querySelector('#studio-root .st-checks').textContent));
  const checks = (await page.textContent(R + '.st-checks')).replace(/\s+/g, ' ');
  ok(/differs from source \$74 million unit differs: source says 74 billion/.test(checks), checks);
  ok(/differs from source 250,000 Australians value differs: source says 300000 jobs/.test(checks), checks);
  await page.fill(R + '.st-field:nth-of-type(1) input', 'Fuel tax credits are not a subsidy and never were one, whatever anyone says');
  await page.waitForFunction(() => /may overflow|characters; about/.test(document.querySelector('#studio-root .st-checks').textContent));
  ok(/Headline is 7\d characters; about 44 fit at 9:16/.test(await page.textContent(R + '.st-checks')));
});
await t('approvals are per component with a reason; an edit invalidates only the changed component; export takes fully approved versions and the ClickUp hand-off is a separate confirmed step', async () => {
  await page.click(R + '.st-railbtn.asset:has-text("Facebook post")');
  await page.waitForSelector(R + '.st-asset');
  await page.click(R + '.st-appr button:has-text("Approve copy")');
  await page.waitForSelector(R + '.st-dialog');
  ok(/never as performance/.test(await page.textContent(R + '.st-dialog')));
  await page.fill(R + '.st-dialog textarea', 'client asked for the plain ask');
  await page.click(R + '.st-dialog button:has-text("Record")');
  await page.waitForFunction(() => /approved.*client asked for the plain ask/.test(document.querySelector('#studio-root .st-approve').textContent));
  await page.click(R + '.st-appr button:has-text("Approve design")');
  await page.fill(R + '.st-dialog textarea', 'fine as is');
  await page.click(R + '.st-dialog button:has-text("Record")');
  await page.waitForFunction(() => (document.querySelector('#studio-root .st-approve').textContent.match(/approved/g) || []).length === 2);
  ok(/export/.test(await page.textContent(R + '.st-head .st-status')) || /review/.test(await page.textContent(R + '.st-head .st-status')));
  await page.fill(R + '.st-field:nth-of-type(3) input', 'Learn more today');
  await page.waitForFunction(() => (document.querySelector('#studio-root .st-approve').textContent.match(/approved/g) || []).length === 1, null, { timeout: 4000 });
  ok(/design.*approved/.test(await page.textContent(R + '.st-approve')) && !/copy.*approved/.test(await page.textContent(R + '.st-appr:first-child')), 'copy approval was invalidated by the copy edit, design stands');
  await page.click(R + '.st-appr button:has-text("Approve copy")');
  await page.fill(R + '.st-dialog textarea', 'ok after the CTA tweak');
  await page.click(R + '.st-dialog button:has-text("Record")');
  await page.waitForFunction(() => (document.querySelector('#studio-root .st-approve').textContent.match(/approved/g) || []).length === 2);
  await page.click(R + '.st-head button:has-text("Export")');
  await page.waitForSelector(R + '.st-dialog');
  const rows = await texts(page, R + '.st-dialog tbody tr');
  const inc = rows.filter(r => /included/.test(r) && !/not included/.test(r)); ok(inc.length === 1 && /Facebook post/.test(inc[0]), JSON.stringify(rows));
  ok(/Export never creates a task or sends anything by itself/.test(await page.textContent(R + '.st-dialog')));
  await shot(page, 'studio-export');
  await page.click(R + '.st-dialog button:has-text("Send to ClickUp")');
  await page.waitForSelector(R + '.st-dialog-box.narrow');
  ok(/Destination:.*Creative/.test(await page.textContent(R + '.st-dialog-box.narrow')) && /Create 1 task/.test(await page.textContent(R + '.st-dialog-box.narrow')));
  await page.click(R + '.st-dialog-box.narrow button:has-text("Cancel")');
  await page.waitForSelector(R + '.st-dialog', { state: 'detached' });
});
await t('rejecting with a standing-sounding reason offers Save as preference with editable wording; declining creates nothing, saving records the scope', async () => {
  await page.click(R + '.st-appr:nth-child(2) button:has-text("Reject")');
  await page.fill(R + '.st-dialog textarea', 'no trucks on HOOF organic, ever');
  await page.click(R + '.st-dialog button:has-text("Record")');
  await page.waitForFunction(() => /Save as a preference\?/.test(document.querySelector('#studio-root .st-thread').textContent));
  const offers = await page.$$(R + '.st-offer .ov-link'); await offers[offers.length - 1].click();
  await page.waitForSelector(R + '.st-offer-box');
  ok(/For hoof: no trucks on HOOF organic, ever\./.test(await page.inputValue(R + '.st-offer-box textarea')));
  await page.click(R + '.st-offer-box button:has-text("Don\'t save")');
  await page.waitForFunction(() => /not saved/.test(document.querySelector('#studio-root .st-thread').textContent));
  const before = await page.evaluate(() => document.querySelectorAll('#studio-root .st-thread .st-msg').length);
  await page.click(R + '.st-appr:nth-child(2) button:has-text("Reject")');
  await page.fill(R + '.st-dialog textarea', 'never show the logo on the left');
  await page.click(R + '.st-dialog button:has-text("Record")');
  await page.waitForFunction(n => document.querySelectorAll('#studio-root .st-thread .st-msg').length >= n + 2, before);
  const offers2 = await page.$$(R + '.st-offer .ov-link'); await offers2[offers2.length - 1].click();
  await page.waitForSelector(R + '.st-offer-box');
  await page.click(R + '.st-offer-box button:has-text("Campaign preference")');
  await page.waitForFunction(() => /saved as a campaign preference/.test(document.querySelector('#studio-root .st-thread').textContent));
  await shot(page, 'studio-partner');
});
await t('a new project from a clear instruction skips directions and produces copy only; an open brief gets directions first', async () => {
  await page.click(R + '.st-head .ov-link:has-text("projects")');
  await page.waitForSelector(R + '.st-lib');
  await page.click(R + '.st-lib-head .btn');
  await page.waitForSelector(R + '.st-intake');
  await page.click(R + '.st-segbtn:has-text("A brief or one line")');
  await page.click(R + '.st-segbtn:has-text("Copy only")');
  await page.fill(R + '.st-intake textarea', 'Write three LinkedIn posts on the $74 billion figure in the HOOF voice');
  ok(/clear instruction/.test(await page.textContent(R + '.st-intake-foot')));
  await page.click(R + '.st-segbtn:has-text("Instagram")'); await page.click(R + '.st-segbtn:has-text("Facebook")');
  await shot(page, 'studio-intake');
  await page.click(R + '.st-intake-foot .btn:has-text("Create project")');
  await page.waitForSelector(R + '.st-asset', { timeout: 6000 });
  eq(await texts(page, R + '.st-rail .st-railbtn.asset'), ['LinkedIn copy 1:1v1']);
  ok(/copy only, no renders/.test(await page.textContent(R + '.st-thread')));
  ok(await page.$(R + '.st-step.skipped'), 'the directions stage is marked skipped');
  await page.click(R + '.st-head .ov-link:has-text("projects")');
  await page.click(R + '.st-lib-head .btn');
  await page.click(R + '.st-segbtn:has-text("A brief or one line")');
  await page.fill(R + '.st-intake textarea', 'Something for Victoria about regional jobs');
  ok(/open brief/.test(await page.textContent(R + '.st-intake-foot')));
  await page.click(R + '.st-intake-foot .btn:has-text("Create project")');
  await page.waitForSelector(R + '.st-dir');
  eq((await texts(page, R + '.st-dir')).length, 2);
  ok(!(await page.$(R + '.st-railbtn.asset')), 'no assets before a direction is chosen');
  await page.click(R + '.st-dir:first-child button:has-text("Choose this direction")');
  await page.waitForSelector(R + '.st-asset', { timeout: 6000 });
  eq((await texts(page, R + '.st-rail .st-railbtn.asset')).length, 3);
});
await t('a legacy pack imports as a project with the original kept and flattened tiles marked not editable', async () => {
  await page.click(R + '.st-head .ov-link:has-text("projects")');
  await page.waitForSelector(R + '.st-lib');
  await page.locator(R + 'tr.st-legacy').first().locator('.ov-link').click();
  await page.waitForSelector(R + '.st-flatnote');
  ok(/flattened legacy tile: the text on the image is not editable/.test(await page.textContent(R + '.st-flatnote')));
  ok(/original release pack is untouched|original release is untouched/.test(await page.textContent(R + '.st-thread')));
  ok(await page.$(R + '.st-field:nth-of-type(1) input:disabled'), 'headline field disabled on a flattened tile');
  ok(/imported from rp_8k2/.test(await page.textContent(R + '.st-head')));
});
await page.close();
await t('a read-only key can review, compare and export but sees no direction composer, approvals or locks', async () => {
  const p2 = await open('read');
  await p2.click(R + '.st-lib tbody tr:first-child .ov-link');
  await p2.waitForSelector(R + '.st-asset');
  ok(!(await p2.$(R + '.st-composer')), 'no composer');
  ok(/needs a full key/.test(await p2.textContent(R + '.st-partner')));
  ok(!(await p2.$(R + '.st-lock')), 'no locks'); ok(!(await p2.$(R + '.st-appr .btn')), 'no approve buttons');
  ok(await p2.$(R + '.st-head button:has-text("Export")'), 'export available');
  ok(!(await p2.$(R + '.st-lib-head .btn')) || true);
  await p2.close();
});
await browser.close(); server.kill();
console.log('\n' + pass + ' passed, ' + fail + ' failed');
process.exit(fail ? 1 : 0);
